#!/usr/bin/env bash
# One-command demo environment: anvil + deploy + seed + web dev server.
# Re-running it is the reset button between recording takes: chain state is
# wiped, contract addresses stay identical (deterministic from a fresh anvil),
# client is re-minted 1,000 mUSDC, freelancer is back to 0.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
RPC="http://127.0.0.1:8545"
DEPLOYMENTS="$ROOT/contracts/deployments/31337.json"

# anvil's well-known dev accounts (local chain only, never real funds)
CLIENT_PK="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
CLIENT_ADDR="0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"

step() { printf '\n\033[1m▸ %s\033[0m\n' "$1"; }

step "stopping anything on ports 8545 (anvil) and 3000 (next dev)"
for PORT in 8545 3000; do
  PIDS="$(lsof -ti tcp:$PORT || true)"
  if [ -n "$PIDS" ]; then
    echo "  killing pid(s) $PIDS on :$PORT"
    kill $PIDS 2>/dev/null || true
    sleep 0.5
  fi
done

step "starting anvil (background)"
anvil --silent &
ANVIL_PID=$!
trap 'kill $ANVIL_PID 2>/dev/null || true' EXIT
for _ in $(seq 1 50); do
  if cast chain-id --rpc-url "$RPC" >/dev/null 2>&1; then break; fi
  sleep 0.2
done
cast chain-id --rpc-url "$RPC" >/dev/null 2>&1 || { echo "anvil did not come up"; exit 1; }

step "deploying MockUSDC + EscrowFactory (0% fee)"
(cd "$ROOT/contracts" && PRIVATE_KEY="$CLIENT_PK" forge script script/Deploy.s.sol --rpc-url "$RPC" --broadcast)

MOCK_USDC="$(node -p 'require(process.argv[1]).mockUSDC' "$DEPLOYMENTS")"
FACTORY="$(node -p 'require(process.argv[1]).escrowFactory' "$DEPLOYMENTS")"

step "minting 1,000 mUSDC to client"
(cd "$ROOT/contracts" && PRIVATE_KEY="$CLIENT_PK" CLIENT_ADDRESS="$CLIENT_ADDR" MOCK_USDC="$MOCK_USDC" \
  forge script script/SeedDemo.s.sol --rpc-url "$RPC" --broadcast)

step "syncing ABIs to web/"
(cd "$ROOT" && node scripts/sync-web.mjs)

step "writing web/.env.local (demo mode ON)"
cat > "$ROOT/web/.env.local" <<EOF
# AUTO-GENERATED by scripts/demo-up.sh — edit .env.example instead.
NEXT_PUBLIC_CHAIN_ID=31337
NEXT_PUBLIC_RPC_URL=http://127.0.0.1:8545
NEXT_PUBLIC_MOCK_USDC=$MOCK_USDC
NEXT_PUBLIC_ESCROW_FACTORY=$FACTORY
NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=demo
NEXT_PUBLIC_DEMO=1
EOF

printf '\n\033[1;32mREADY.\033[0m Open these side by side (same Chrome profile is fine):\n'
printf '  CLIENT      →  http://localhost:3000/?role=client\n'
printf '  FREELANCER  →  http://localhost:3000/?role=freelancer\n'
printf 'Retake reset: Ctrl-C here, run "pnpm demo:up" again, reload both windows.\n\n'

step "starting web dev server (Ctrl-C stops everything, including anvil)"
cd "$ROOT" && pnpm --filter web dev
